# Generated by Django 5.2.1 on 2025-06-04 02:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_invoiceitem'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoiceitem',
            name='either_service_or_product_or_custom_description_required',
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0, help_text='Current quantity of the product in stock.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', False), ('service__isnull', True)), models.Q(('product__isnull', True), ('service__isnull', False)), models.Q(('description__gt', ''), ('description__isnull', False), ('product__isnull', True), ('service__isnull', True)), _connector='OR'), name='either_service_or_product_or_custom_description_required'),
        ),
    ]
