# Generated by Django 5.2.1 on 2025-06-12 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_purchaseorder_purchaseorderitem_supplierpayment'),
        ('doctors', '0002_doctor_user'),
        ('patients', '0002_alter_patient_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='patients.patient'),
        ),
    ]
