# Generated by Django 5.2.1 on 2025-06-12 11:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_purchaseorderitem_quantity_received_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('ADDITION', 'Manual Addition'), ('SUBTRACTION', 'Manual Subtraction')], max_length=11)),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('DAMAGED', 'Damaged Goods'), ('EXPIRED', 'Expired Stock'), ('STOCK_TAKE', 'Stock Take Correction'), ('INITIAL_STOCK', 'Initial Stock Setup'), ('OTHER', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text="Provide details, especially if reason is 'Other'.")),
                ('adjustment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('adjusted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='billing.product')),
            ],
            options={
                'ordering': ['-adjustment_date'],
            },
        ),
    ]
