# Generated by Django 5.2.1 on 2025-06-13 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_stockadjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItemTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='stockitem',
            options={'ordering': ['date_received'], 'verbose_name': 'Stock Item / Batch', 'verbose_name_plural': 'Stock Items / Batches'},
        ),
        migrations.RemoveConstraint(
            model_name='invoiceitem',
            name='item_source_exclusive_or_custom_description',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='product',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='stock_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='billing.stockitem'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='quantity',
            field=models.PositiveIntegerField(help_text='The total quantity received in this batch.'),
        ),
        migrations.AddField(
            model_name='stockitemtransaction',
            name='invoice_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='billing.invoiceitem'),
        ),
        migrations.AddField(
            model_name='stockitemtransaction',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='billing.stockitem'),
        ),
    ]
