# Generated by Django 5.2.1 on 2025-06-03 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('RECEP', 'Receptionist'), ('ASSIST', 'Dental Assistant'), ('HYGIEN', 'Dental Hygienist'), ('MANAGER', 'Clinic Manager'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('date_joined', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the staff member currently employed?')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'ordering': ['name'],
            },
        ),
    ]
