# Generated by Django 5.2.1 on 2025-06-13 23:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staffmember_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: +91 followed by 10 digits.', regex='^\\+91\\d{10}$')]),
        ),
    ]
