# Generated by Django 5.2.1 on 2025-06-13 16:15

import dental_records.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalRecord',
            fields=[
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dental_record', serialize=False, to='appointments.appointment')),
                ('clinical_notes', models.TextField(blank=True, help_text="Doctor's clinical notes, observations, diagnosis for this visit.", null=True)),
                ('treatments_performed', models.TextField(blank=True, help_text="Details of treatments performed during this visit (e.g., 'Scaling and Polishing', 'Composite filling on #24 MOD').", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dental Record',
                'verbose_name_plural': 'Dental Records',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('dental_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='prescription', serialize=False, to='dental_records.dentalrecord')),
                ('date_prescribed', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='General notes for the entire prescription.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
            },
        ),
        migrations.CreateModel(
            name='DentalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=dental_records.models.dental_image_path)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dental_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dental_records.dentalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(blank=True, help_text="e.g., '500mg', '1 tablet'", max_length=100)),
                ('frequency', models.CharField(blank=True, help_text="e.g., '3 times a day', 'Once at night'", max_length=100)),
                ('duration', models.CharField(blank=True, help_text="e.g., 'for 5 days', 'for 1 week'", max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Specific instructions for this medication.', null=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dental_records.prescription')),
            ],
            options={
                'verbose_name': 'Prescription Item',
                'verbose_name_plural': 'Prescription Items',
            },
        ),
    ]
