# Generated by Django 5.2.1 on 2025-06-03 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalRecord',
            fields=[
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dental_record', serialize=False, to='appointments.appointment')),
                ('clinical_notes', models.TextField(blank=True, help_text="Doctor's clinical notes, observations, diagnosis for this visit.", null=True)),
                ('treatments_performed', models.TextField(blank=True, help_text="Details of treatments performed during this visit (e.g., 'Scaling and Polishing', 'Composite filling on #24 MOD').", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dental Record',
                'verbose_name_plural': 'Dental Records',
            },
        ),
    ]
