# Generated by Django 5.2.1 on 2025-06-08 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('dental_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='prescription', serialize=False, to='dental_records.dentalrecord')),
                ('date_prescribed', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='General notes for the entire prescription.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(blank=True, help_text="e.g., '500mg', '1 tablet'", max_length=100)),
                ('frequency', models.CharField(blank=True, help_text="e.g., '3 times a day', 'Once at night'", max_length=100)),
                ('duration', models.CharField(blank=True, help_text="e.g., 'for 5 days', 'for 1 week'", max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Specific instructions for this medication.', null=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dental_records.prescription')),
            ],
            options={
                'verbose_name': 'Prescription Item',
                'verbose_name_plural': 'Prescription Items',
            },
        ),
    ]
