# Generated by Django 5.2.1 on 2025-06-10 01:58

import dental_records.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_records', '0002_prescription_prescriptionitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=dental_records.models.dental_image_path)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dental_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dental_records.dentalrecord')),
            ],
        ),
    ]
