# Generated by Django 5.2.1 on 2025-06-06 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about the lab, like specialties or turnaround times.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this lab currently used by the clinic?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dental Lab',
                'verbose_name_plural': 'Dental Labs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(help_text="e.g., 'Zirconia Crown', 'PFM Bridge', 'Complete Denture'", max_length=100)),
                ('description', models.TextField(help_text='Detailed instructions for the lab, including tooth numbers, shade, materials, etc.')),
                ('status', models.CharField(choices=[('CREATED', 'Case Created'), ('SENT', 'Sent to Lab'), ('RECEIVED', 'Received from Lab'), ('COMPLETED', 'Completed / Fitted'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=10)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost of the lab work.', max_digits=10, null=True)),
                ('date_sent', models.DateField(blank=True, null=True)),
                ('date_due', models.DateField(blank=True, help_text='Expected return date from the lab.', null=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, help_text='Doctor who ordered the case.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_cases', to='doctors.doctor')),
                ('lab', models.ForeignKey(help_text='The dental lab this case was sent to.', on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='lab_cases.dentallab')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_cases', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Lab Case',
                'verbose_name_plural': 'Lab Cases',
                'ordering': ['-date_due', '-date_sent'],
            },
        ),
    ]
