# Generated by Django 5.2.1 on 2025-06-12 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_user'),
        ('lab_cases', '0001_initial'),
        ('patients', '0002_alter_patient_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labcase',
            name='doctor',
            field=models.ForeignKey(blank=True, help_text='Doctor who ordered the case.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_cases', to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='labcase',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_cases', to='patients.patient'),
        ),
    ]
