# Generated by Django 5.2.1 on 2025-06-03 02:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True, help_text='Reason for the visit', null=True)),
                ('status', models.CharField(choices=[('SCH', 'Scheduled'), ('CNF', 'Confirmed'), ('CMP', 'Completed'), ('CAN', 'Cancelled'), ('NOS', 'No Show')], default='SCH', max_length=3)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the appointment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
            options={
                'ordering': ['appointment_datetime'],
            },
        ),
    ]
