# Generated by Django 5.2.1 on 2025-06-13 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('contact_number', models.CharField(blank=True, help_text='Enter 10-digit mobile number.', max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('place', models.CharField(blank=True, default='', help_text='City or town of residence.', max_length=100)),
                ('pincode', models.CharField(blank=True, help_text='Enter 6-digit PIN code.', max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='PIN code must be exactly 6 digits.', regex='^\\d{6}$')])),
                ('allergies', models.TextField(blank=True, help_text='e.g., Penicillin, Aspirin', null=True)),
                ('ongoing_conditions', models.TextField(blank=True, help_text='e.g., Diabetes, Hypertension', null=True)),
                ('medications', models.TextField(blank=True, help_text='List any current medications.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
