# Generated by Django 5.2.1 on 2025-06-13 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='patient',
            name='pincode',
            field=models.CharField(blank=True, help_text='Enter 6-digit PIN code.', max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='PIN code must be exactly 6 digits.', regex='^\\d{6}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, help_text='e.g., Penicillin, Aspirin', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Enter 10-digit mobile number.', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medications',
            field=models.TextField(blank=True, help_text='List any current medications.', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ongoing_conditions',
            field=models.TextField(blank=True, help_text='e.g., Diabetes, Hypertension', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='place',
            field=models.CharField(blank=True, default='', help_text='City or town of residence.', max_length=100),
        ),
    ]
