# Generated by Django 5.2.3 on 2025-06-15 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patient_contact_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='created_at',
            new_name='registration_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+91\\d{10}$', 'Contact number must be in +91XXXXXXXXXX format.')]),
        ),
    ]
