# Generated by Django 5.2.3 on 2025-06-15 01:51

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='registration_date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN'),
        ),
    ]
