# Generated by Django 5.2.3 on 2025-06-15 03:44

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_rename_registration_date_patient_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Enter phone number with country code.', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pincode',
            field=models.CharField(blank=True, help_text='Enter postal code.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
