# Generated by Django 5.2.1 on 2025-06-13 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(choices=[('GD', 'General Dentistry'), ('ORTHO', 'Orthodontics'), ('ENDO', 'Endodontics'), ('PERIO', 'Periodontics'), ('PROSTHO', 'Prosthodontics'), ('PEDO', 'Pediatric Dentistry'), ('OS', 'Oral Surgery'), ('OTHER', 'Other')], default='GD', max_length=10)),
                ('contact_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('credentials', models.TextField(blank=True, null=True)),
                ('availability_notes', models.TextField(blank=True, help_text='E.g., Mon-Fri 9am-5pm', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
