# Generated by Django 5.2.1 on 2025-06-14 03:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_doctor_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='contact_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: +91 followed by 10 digits.', regex='^\\+91\\d{10}$')]),
        ),
    ]
